# Generated by Django 2.2.dev20180718181542 on 2018-07-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARP_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_num', models.IntegerField()),
                ('jason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ARP_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.TextField()),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('check', models.BooleanField(default=True)),
            ],
        ),
    ]
