# Generated by Django 2.2.dev20180718181542 on 2018-07-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
            ],
        ),
    ]
