# Generated by Django 2.2.dev20180718181542 on 2018-07-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
