# Generated by Django 2.2.dev20180718181542 on 2018-07-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simap', '0002_auto_20180725_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
